# Global Error code and Error message

ERROR_ARGUMENT=30
ERROR_ARGUMENT_MESSAGE="Parameter error!"

ERROR_USER_EXIST=1000
ERROR_USER_EXIST_MESSAGE="This email or phone is existed!"

ERROR_USER_NOT_EXIST=1010
ERROR_USER_NOT_EXIST_MESSAGE="This User not exist!"

ERROR_LOGIN=1020
ERROR_LOGIN_MESSAGE="Login failed！"

ERROR_USERNAME_OR_PASSWORD=1030
ERROR_USERNAME_OR_PASSWORD_MESSAGE="Username or password error!"

ERROR_EMPTY_EMAIL_OR_PASSWORD=1040
ERROR_EMPTY_EMAIL_OR_PASSWORD_MESSAGE="Username or password cannot be empty!"

ERROR_ACCOUNT_BOUND=1050
ERROR_ACCOUNT_BOUND_MESSAGE="The account has been bound"

ERROR_SAVE_SESSION=1060
ERROR_SAVE_SESSION_MESSAGE="Login failed！"