# Global Error code and Error message

ERROR_ARGUMENT=30
ERROR_ARGUMENT_MESSAGE="Parameter error!"

ERROR_TOO_FAST=50
ERROR_TOO_FAST_MESSAGE="Interface calls are too frequent!"

ERROR_PARAMS_ENCRYPT=60
ERROR_PARAMS_ENCRYPT_MESSAGE="Incorrect parameter encryption！"

ERROR_PARAMS_SIGN=70
ERROR_PARAMS_SIGN_MESSAGE="Incorrect parameter signature！"

ERROR_UNAUTHORIZED=401
ERROR_UNAUTHORIZED_MESSAGE="Please login first!"

ERROR_USER_EXIST=1000
ERROR_USER_EXIST_MESSAGE="This email or phone is existed!"

ERROR_USER_NOT_EXIST=1010
ERROR_USER_NOT_EXIST_MESSAGE="This User not exist!"

ERROR_LOGIN=1020
ERROR_LOGIN_MESSAGE="Login failed！"

ERROR_USERNAME_OR_PASSWORD=1030
ERROR_USERNAME_OR_PASSWORD_MESSAGE="Username or password error!"

ERROR_EMPTY_EMAIL_OR_PASSWORD=1040
ERROR_EMPTY_EMAIL_OR_PASSWORD_MESSAGE="Username or password cannot be empty!"

ERROR_ACCOUNT_BOUND=1050
ERROR_ACCOUNT_BOUND_MESSAGE="The account has been bound"

ERROR_SAVE_SESSION=1060
ERROR_SAVE_SESSION_MESSAGE="Login failed!"

ERROR_EMAIL_SEND=1070
ERROR_EMAIL_SEND_MESSAGE="Failed to send mail!"

ERROR_EMAIL_ALREADY_CONFIRM=1070
ERROR_EMAIL_ALREADY_CONFIRM_MESSAGE="The email has been verified, please do not verify again!"

ERROR_CODE=1080
ERROR_CODE_MEAASGE="Verification code error!"

ERROR_EXPIRED_CODE=1090
ERROR_EXPIRED_CODE_MESSAGE="Verification code expired!"